name: zaimuniversity
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^5.1.0
  logging: ^1.2.0
  path_provider: ^2.1.1
  logger: ^2.5.0
  vm_service: 14.3.1
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - ./.env
    - env/.env
    - assets/images/

dependency_overrides:
  async: ^2.13.0
  material_color_utilities: ^0.12.0
  vector_math: ^2.1.5
  fake_async: ^1.3.3
  leak_tracker: ^10.0.9
  lints: ^6.0.0
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
