name: zaimuniversity
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^5.1.0
  logging: ^1.2.0
  path_provider: ^2.1.1
  logger: ^2.5.0
  vm_service: 14.3.1
  flutter_svg: ^2.0.9
  image_picker: ^1.1.2
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/app_icons/playstore.png"
  image_path_ios: "assets/app_icons/appstore.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

flutter:
  uses-material-design: true
  assets:
    - ./.env
    - env/.env
    - assets/images/
    - assets/app_icons/appstore.png
    - assets/app_icons/playstore.png
    - assets/app_icons/android/
    - assets/app_icons/Assets.xcassets/

dependency_overrides:
  async: ^2.13.0
  material_color_utilities: ^0.12.0
  vector_math: ^2.1.5
  fake_async: ^1.3.3
  leak_tracker: ^10.0.9
  lints: ^6.0.0
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
